module.exports = {
    rules: {
        camelcase: 'off',
        'class-methods-use-this': 'off',
        'comma-dangle': ['error', 'always-multiline'],
        'consistent-return': 'off',
        'consistent-this': [1, 'self'],
        curly: ['error', 'all'],
        'no-console': ['error', {allow: ['debug', 'error']}],
        'func-names': 'off',
        'global-require': 'off',
        'import/no-dynamic-require': 'off',
        'import/no-extraneous-dependencies': 'off',
        'import/no-unresolved': 'off',
        'jsx-a11y/click-events-have-key-events': 'off',
        'jsx-a11y/label-has-for': 'off',

        // Enforce indentation of 4 spaces; the third option parameter was copied from Airbnb:
        // https://github.com/airbnb/javascript/blob/60b96d322277c4c71a21a05caba8eb3320e0e3fa/packages/eslint-config-airbnb-base/rules/style.js#L120-L145
        indent: ['error', 4, {
            SwitchCase: 1,
            VariableDeclarator: 1,
            outerIIFEBody: 1,
            FunctionDeclaration: {
                parameters: 1,
                body: 1,
            },
            FunctionExpression: {
                parameters: 1,
                body: 1,
            },
            CallExpression: {
                arguments: 1,
            },
            ArrayExpression: 1,
            ObjectExpression: 1,
            ImportDeclaration: 1,
            flatTernaryExpressions: false,

            // list derived from https://github.com/benjamn/ast-types/blob/HEAD/def/jsx.js
            // eslint-disable-next-line max-len
            ignoredNodes: ['JSXElement', 'JSXElement > *', 'JSXAttribute', 'JSXIdentifier', 'JSXNamespacedName', 'JSXMemberExpression', 'JSXSpreadAttribute', 'JSXExpressionContainer', 'JSXOpeningElement', 'JSXClosingElement', 'JSXText', 'JSXEmptyExpression', 'JSXSpreadChild'],
            ignoreComments: false,
        }],

        // Airbnb didn't want this rule to be enabled even though it complies with their styleguide - so we're adding it
        // https://github.com/airbnb/javascript/pull/1994
        'lines-around-comment': ['error', {
            beforeLineComment: true,
            allowBlockStart: true,
            allowObjectStart: true,
            allowArrayStart: true,
            allowClassStart: true,
        }],
        'no-multiple-empty-lines': ['error', {max: 1}],
        'max-len': ['warn', {
            code: 190,
        }],
        'new-cap': 'off',
        'no-alert': 'off',
        'no-mixed-operators': ['warn', {
            groups: [
                ['+', '-', '*', '/', '%', '**'],
                ['&', '|', '^', '~', '<<', '>>', '>>>'],
                ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
                ['&&', '||'],
                ['in', 'instanceof'],
            ],
            allowSamePrecedence: false,
        }],
        'no-plusplus': 'off',
        'no-return-assign': 'off',
        'object-curly-spacing': ['error', 'never'],

        // Require space before function opening parenthesis
        'space-before-function-paren': ['error', {
            anonymous: 'always',
            named: 'never',
        }],
        strict: ['error', 'never'],
        'valid-jsdoc': ['error', {
            requireParamDescription: false,
            requireReturnDescription: false,
            requireReturn: false,
        }],
        'vars-on-top': 'off',

        // This enforces wrapping always the function expression.
        'wrap-iife': ['error', 'inside'],

        // =============================================
        // CORE JAVASCRIPT RULES (from eslint-config-airbnb-base)
        // =============================================

        // Best Practices
        'array-callback-return': ['error', {allowImplicit: true}],
        'block-scoped-var': 'error',
        complexity: ['off', 20],
        'default-case': ['error', {commentPattern: '^no default$'}],
        'default-case-last': 'error',
        'default-param-last': 'error',
        'dot-notation': ['error', {allowKeywords: true}],
        'dot-location': ['error', 'property'],
        eqeqeq: ['error', 'always', {null: 'ignore'}],
        'grouped-accessor-pairs': 'error',
        'guard-for-in': 'error',
        'max-classes-per-file': ['error', 1],
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-constructor-return': 'error',
        'no-div-regex': 'off',
        'no-else-return': ['error', {allowElseIf: false}],
        'no-empty-function': ['error', {
            allow: [
                'arrowFunctions',
                'functions',
                'methods',
            ],
        }],
        'no-empty-pattern': 'error',
        'no-eq-null': 'off',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-extra-label': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'error',
        'no-global-assign': ['error', {exceptions: []}],
        'no-native-reassign': 'off',
        'no-implicit-coercion': ['off', {
            boolean: false,
            number: true,
            string: true,
            allow: [],
        }],
        'no-implicit-globals': 'off',
        'no-implied-eval': 'error',
        'no-iterator': 'error',
        'no-labels': ['error', {allowLoop: false, allowSwitch: false}],
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-magic-numbers': ['off', {
            ignore: [],
            ignoreArrayIndexes: true,
            enforceConst: true,
            detectObjects: false,
        }],
        'no-multi-spaces': ['error', {
            ignoreEOLComments: false,
        }],
        'no-multi-str': 'error',
        'no-new': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-octal': 'error',
        'no-octal-escape': 'error',
        'no-param-reassign': ['error', {
            props: true,
            ignorePropertyModificationsFor: [
                'acc', // for reduce accumulators
                'accumulator', // for reduce accumulators
                'e', // for e.returnvalue
                'ctx', // for Koa routing
                'context', // for Koa routing
                'req', // for Express requests
                'request', // for Express requests
                'res', // for Express responses
                'response', // for Express responses
                '$scope', // for Angular 1 scopes
                'staticContext', // for ReactRouter context
            ],
        }],
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-restricted-properties': ['error',
            {
                object: 'arguments',
                property: 'callee',
                message: 'arguments.callee is deprecated',
            },
            {
                object: 'global',
                property: 'isFinite',
                message: 'Please use Number.isFinite instead',
            },
            {
                object: 'self',
                property: 'isFinite',
                message: 'Please use Number.isFinite instead',
            },
            {
                object: 'window',
                property: 'isFinite',
                message: 'Please use Number.isFinite instead',
            },
            {
                object: 'global',
                property: 'isNaN',
                message: 'Please use Number.isNaN instead',
            },
            {
                object: 'self',
                property: 'isNaN',
                message: 'Please use Number.isNaN instead',
            },
            {
                object: 'window',
                property: 'isNaN',
                message: 'Please use Number.isNaN instead',
            },
            {
                property: '__defineGetter__',
                message: 'Please use Object.defineProperty instead.',
            },
            {
                property: '__defineSetter__',
                message: 'Please use Object.defineProperty instead.',
            },
            {
                object: 'Math',
                property: 'pow',
                message: 'Use the exponentiation operator (**) instead.',
            },
        ],
        'no-script-url': 'error',
        'no-self-assign': ['error', {props: true}],
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unmodified-loop-condition': 'off',
        'no-unused-expressions': ['error', {
            allowShortCircuit: false,
            allowTernary: false,
            allowTaggedTemplates: false,
        }],
        'no-unused-labels': 'error',
        'no-useless-call': 'off',
        'no-useless-catch': 'error',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-useless-return': 'error',
        'no-void': 'error',
        'no-warning-comments': ['off', {terms: ['todo', 'fixme', 'xxx'], location: 'start'}],
        'no-with': 'error',
        'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
        'prefer-named-capture-group': 'off',
        radix: 'error',
        'require-await': 'off',
        'require-unicode-regexp': 'off',
        yoda: 'error',

        // Error Prevention
        'for-direction': 'error',
        'getter-return': ['error', {allowImplicit: true}],
        'no-async-promise-executor': 'error',
        'no-await-in-loop': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': ['error', 'always'],
        'no-constant-condition': 'warn',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-dupe-args': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-extra-parens': ['off', 'all', {
            conditionalAssign: true,
            nestedBinaryExpressions: false,
            returnAssign: false,
            ignoreJSX: 'all', // delegate to eslint-plugin-react
            enforceForArrowConditionals: false,
        }],
        'no-extra-semi': 'error',
        'no-func-assign': 'error',
        'no-import-assign': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-obj-calls': 'error',
        'no-promise-executor-return': 'error',
        'no-prototype-builtins': 'error',
        'no-regex-spaces': 'error',
        'no-setter-return': 'error',
        'no-sparse-arrays': 'error',
        'no-template-curly-in-string': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'no-unreachable-loop': ['error', {
            ignore: [], // WhileStatement, DoWhileStatement, ForStatement, ForInStatement, ForOfStatement
        }],
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': ['error', {disallowArithmeticOperators: true}],
        'no-unused-private-class-members': 'off',
        'no-useless-backreference': 'error',
        'no-negated-in-lhs': 'off',
        'require-atomic-updates': 'off',
        'use-isnan': 'error',
        'valid-typeof': ['error', {requireStringLiterals: true}],

        // Variables
        'init-declarations': 'off',
        'no-catch-shadow': 'off',
        'no-delete-var': 'error',
        'no-label-var': 'error',
        'no-restricted-globals': [
            'error',
            {
                name: 'isFinite',
                message:
                    'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
            },
            {
                name: 'isNaN',
                message:
                    'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
            },
        ].concat(require('confusing-browser-globals')),
        'no-shadow': 'error',
        'no-shadow-restricted-names': 'error',
        'no-undef': 'error',
        'no-undef-init': 'error',
        'no-undefined': 'off',
        'no-unused-vars': ['error', {vars: 'all', args: 'after-used', ignoreRestSiblings: true}],
        'no-use-before-define': ['error', {functions: true, classes: true, variables: true}],

        // Node.js
        'callback-return': 'off',
        'handle-callback-err': 'off',
        'no-buffer-constructor': 'error',
        'no-mixed-requires': ['off', false],
        'no-new-require': 'error',
        'no-path-concat': 'error',
        'no-process-env': 'off',
        'no-process-exit': 'off',
        'no-restricted-modules': 'off',
        'no-sync': 'off',

        // Import rules
        'import/named': 'error',
        'import/default': 'off',
        'import/namespace': 'off',
        'import/export': 'error',
        'import/no-named-as-default': 'error',
        'import/no-named-as-default-member': 'error',
        'import/no-deprecated': 'off',
        'import/no-mutable-exports': 'error',
        'import/no-commonjs': 'off',
        'import/no-amd': 'error',
        'import/no-nodejs-modules': 'off',
        'import/first': 'error',
        'import/no-duplicates': 'error',
        'import/no-namespace': 'off',
        'import/extensions': ['error', 'ignorePackages', {
            js: 'never',
            mjs: 'never',
            jsx: 'never',
        }],
        'import/order': ['error', {groups: [['builtin', 'external', 'internal']]}],
        'import/newline-after-import': 'error',
        'import/prefer-default-export': 'error',
        'import/no-restricted-paths': 'off',
        'import/max-dependencies': 'off',
        'import/no-absolute-path': 'error',
        'import/no-internal-modules': ['off', {
            allow: [],
        }],
        'import/unambiguous': 'off',
        'import/no-webpack-loader-syntax': 'error',
        'import/no-unassigned-import': 'off',
        'import/no-named-default': 'error',
        'import/exports-last': 'off',
        'import/group-exports': 'off',
        'import/no-default-export': 'off',
        'import/no-named-export': 'off',
        'import/no-self-import': 'error',
        'import/no-cycle': ['error', {maxDepth: '∞'}],
        'import/no-useless-path-segments': ['error', {commonjs: true}],
        'import/dynamic-import-chunkname': ['off', {
            importFunctions: [],
            webpackChunknameFormat: '[0-9a-zA-Z-_/.]+',
        }],
        'import/no-relative-parent-imports': 'off',
        'import/no-unused-modules': ['off', {
            ignoreExports: [],
            missingExports: true,
            unusedExports: true,
        }],
        'import/no-import-module-exports': ['error', {
            exceptions: [],
        }],
        'import/no-relative-packages': 'error',

        // Additional Style Rules
        'array-bracket-spacing': ['error', 'never'],
        'block-spacing': ['error', 'always'],
        'brace-style': ['error', '1tbs', {allowSingleLine: true}],
        'capitalized-comments': ['off', 'never'],
        'comma-spacing': ['error', {before: false, after: true}],
        'comma-style': ['error', 'last', {
            exceptions: {
                ArrayExpression: false,
                ArrayPattern: false,
                ArrowFunctionExpression: false,
                CallExpression: false,
                FunctionDeclaration: false,
                FunctionExpression: false,
                ImportDeclaration: false,
                ObjectExpression: false,
                ObjectPattern: false,
                VariableDeclaration: false,
                NewExpression: false,
            },
        }],
        'computed-property-spacing': ['error', 'never'],
        'eol-last': ['error', 'always'],
        'func-style': ['off', 'expression'],
        'function-paren-newline': ['error', 'consistent'],
        'id-blacklist': 'off',
        'id-length': 'off',
        'id-match': 'off',
        'implicit-arrow-linebreak': ['error', 'beside'],
        'jsx-quotes': ['off', 'prefer-double'],
        'key-spacing': ['error', {beforeColon: false, afterColon: true}],
        'keyword-spacing': ['error', {
            before: true,
            after: true,
            overrides: {
                return: {after: true},
                throw: {after: true},
                case: {after: true},
            },
        }],
        'line-comment-position': ['off', {
            position: 'above',
            ignorePattern: '',
            applyDefaultPatterns: true,
        }],
        'linebreak-style': ['error', 'unix'],
        'lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: false}],
        'max-nested-callbacks': 'off',
        'max-params': ['off', 3],
        'max-statements': ['off', 10],
        'max-statements-per-line': ['off', {max: 1}],
        'multiline-comment-style': ['off', 'starred-block'],
        'multiline-ternary': ['off', 'never'],
        'new-parens': 'error',
        'newline-after-var': 'off',
        'newline-before-return': 'off',
        'newline-per-chained-call': ['error', {ignoreChainWithDepth: 4}],
        'no-array-constructor': 'error',
        'no-bitwise': 'error',
        'no-continue': 'error',
        'no-inline-comments': 'off',
        'no-lonely-if': 'error',
        'no-mixed-spaces-and-tabs': 'error',
        'no-multi-assign': ['error'],
        'no-negated-condition': 'off',
        'no-nested-ternary': 'error',
        'no-new-object': 'error',
        'no-spaced-func': 'error',
        'no-tabs': 'error',
        'no-ternary': 'off',
        'no-trailing-spaces': ['error', {
            skipBlankLines: false,
            ignoreComments: false,
        }],
        'no-underscore-dangle': ['error', {
            allow: [],
            allowAfterThis: false,
            allowAfterSuper: false,
            enforceInMethodNames: true,
        }],
        'no-unneeded-ternary': ['error', {defaultAssignment: false}],
        'no-whitespace-before-property': 'error',
        'nonblock-statement-body-position': ['error', 'beside', {overrides: {}}],
        'object-curly-newline': ['error', {
            ObjectExpression: {minProperties: 4, multiline: true, consistent: true},
            ObjectPattern: {minProperties: 4, multiline: true, consistent: true},
            ImportDeclaration: {minProperties: 4, multiline: true, consistent: true},
            ExportDeclaration: {minProperties: 4, multiline: true, consistent: true},
        }],
        'object-property-newline': ['error', {
            allowAllPropertiesOnSameLine: true,
        }],
        'one-var': ['error', 'never'],
        'one-var-declaration-per-line': ['error', 'always'],
        'operator-assignment': ['error', 'always'],
        'operator-linebreak': ['error', 'before', {overrides: {'=': 'none'}}],
        'padded-blocks': ['error', {
            blocks: 'never',
            classes: 'never',
            switches: 'never',
        }, {
            allowSingleLineBlocks: true,
        }],
        'padding-line-between-statements': 'off',
        'prefer-exponentiation-operator': 'error',
        'prefer-object-spread': 'error',
        'quote-props': ['error', 'as-needed', {keywords: false, unnecessary: true, numbers: false}],
        quotes: ['error', 'single', {avoidEscape: true}],
        'semi-spacing': ['error', {before: false, after: true}],
        'semi-style': ['error', 'last'],
        semi: ['error', 'always'],
        'sort-keys': ['off', 'asc', {caseSensitive: false, natural: true}],
        'sort-vars': 'off',
        'space-before-blocks': 'error',
        'space-in-parens': ['error', 'never'],
        'space-infix-ops': 'error',
        'space-unary-ops': ['error', {
            words: true,
            nonwords: false,
            overrides: {
            },
        }],
        'spaced-comment': ['error', 'always', {
            line: {
                exceptions: ['-', '+'],
                markers: ['=', '!'], // space here to support sprockets directives
            },
            block: {
                exceptions: ['-', '+'],

                // space here to support sprockets directives and flow comment types
                markers: ['=', '!', ':', '::'],
                balanced: true,
            },
        }],
        'switch-colon-spacing': ['error', {after: true, before: false}],
        'template-tag-spacing': ['error', 'never'],
        'unicode-bom': ['error', 'never'],

        // JSX A11y rules
        'jsx-a11y/accessible-emoji': 'off',
        'jsx-a11y/alt-text': ['error', {
            elements: ['img', 'object', 'area', 'input[type="image"]'],
            img: [],
            object: [],
            area: [],
            'input[type="image"]': [],
        }],
        'jsx-a11y/anchor-has-content': ['error', {components: []}],
        'jsx-a11y/anchor-is-valid': ['error', {
            components: ['Link'],
            specialLink: ['hrefLeft', 'hrefRight'],
            aspects: ['noHref', 'invalidHref', 'preferButton'],
        }],
        'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
        'jsx-a11y/aria-props': 'error',
        'jsx-a11y/aria-proptypes': 'error',
        'jsx-a11y/aria-role': ['error', {ignoreNonDOM: false}],
        'jsx-a11y/aria-unsupported-elements': 'error',
        'jsx-a11y/autocomplete-valid': ['off', {
            inputComponents: [],
        }],
        'jsx-a11y/heading-has-content': ['error', {components: ['']}],
        'jsx-a11y/html-has-lang': 'error',
        'jsx-a11y/iframe-has-title': 'error',
        'jsx-a11y/img-redundant-alt': 'error',
        'jsx-a11y/interactive-supports-focus': 'error',
        'jsx-a11y/label-has-associated-control': ['error', {
            labelComponents: [],
            labelAttributes: [],
            controlComponents: [],
            assert: 'both',
            depth: 25,
        }],
        'jsx-a11y/lang': 'error',
        'jsx-a11y/media-has-caption': ['error', {
            audio: [],
            video: [],
            track: [],
        }],
        'jsx-a11y/mouse-events-have-key-events': 'error',
        'jsx-a11y/no-access-key': 'error',
        'jsx-a11y/no-autofocus': ['error', {ignoreNonDOM: true}],
        'jsx-a11y/no-distracting-elements': ['error', {
            elements: ['marquee', 'blink'],
        }],
        'jsx-a11y/no-interactive-element-to-noninteractive-role': ['error', {
            tr: ['none', 'presentation'],
        }],
        'jsx-a11y/no-noninteractive-element-interactions': ['error', {
            handlers: [
                'onClick',
                'onMouseDown',
                'onMouseUp',
                'onKeyPress',
                'onKeyDown',
                'onKeyUp',
            ],
        }],
        'jsx-a11y/no-noninteractive-element-to-interactive-role': ['error', {
            ul: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
            ol: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
            li: ['menuitem', 'option', 'row', 'tab', 'treeitem'],
            table: ['grid'],
            td: ['gridcell'],
        }],
        'jsx-a11y/no-noninteractive-tabindex': ['error', {
            tags: [],
            roles: ['tabpanel'],
        }],
        'jsx-a11y/no-onchange': 'off',
        'jsx-a11y/no-redundant-roles': 'error',
        'jsx-a11y/no-static-element-interactions': ['error', {
            handlers: [
                'onClick',
                'onMouseDown',
                'onMouseUp',
                'onKeyPress',
                'onKeyDown',
                'onKeyUp',
            ],
        }],
        'jsx-a11y/role-has-required-aria-props': 'error',
        'jsx-a11y/role-supports-aria-props': 'error',
        'jsx-a11y/scope': 'error',
        'jsx-a11y/tabindex-no-positive': 'error',
    },
};
