name: ESLint

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: eslint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup Node
        # v4
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: 20

      - name: Run npm install
        uses: nick-fields/retry@3f757583fb1b1f940bc8ef4bf4734c8dc02a5847
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: npm ci

      - name: Run ESLint
        run: npm run lint
